name: noteapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  get: ^4.6.5
  firebase_core: ^1.17.0
  google_sign_in: ^5.3.2
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  glassmorphism: ^3.0.0
  flutter_secure_storage: ^5.0.2
  share: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1
  intl: ^0.17.0
  fab_circular_menu: ^1.0.2
  timeago: ^3.2.2

  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/

  fonts:
    - family: roynh
      fonts:
        - asset: assets/fonts/roynh.ttf